name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera o Snake
        uses: Platane/snk@v3
        with:
          github_user_name: gabrieldani
          outputs: |
            ./output/github-contribution-grid-snake.svg
          color_snake: '#bb9af7'
          color_dots: '#7aa2f7'
          color_empty: '#3b4261'
          background: '#1a1b26'

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "output/github-contribution-grid-snake.svg"
